Repository commercelayer/mfe-checkout, pull requests merged in 2023-10, with the labels that each got.

#362 Add native support to Klarna payment gateway
  .circleci/config.yml
  README.md
  package.json
  pnpm-lock.yaml
  specs/e2e/payments-klarna.spec.ts
  specs/fixtures/CheckoutPage.ts
Labels: Enahancement

#363 Remove klarna alert from README
  README.md
Labels: documentation

#369 Keep active class on shipping method button after multiple clicks
  .circleci/config.yml
  components/composite/StepShipping/index.tsx
  components/composite/StepShipping/styled.tsx
  components/data/AppProvider/utils.ts
  package.json
  pnpm-lock.yaml
Labels: bug

#370 Update all dependencies to their latest
  .eslintrc.json
  components/composite/Checkout/index.tsx
  components/composite/StepComplete/SupportMessage/index.tsx
  components/composite/StepComplete/index.tsx
  components/composite/StepCustomer/CheckoutAddresses.tsx
  components/composite/StepCustomer/CheckoutCustomerAddresses.tsx
  components/composite/StepPayment/index.tsx
  components/composite/StepPlaceOrder/index.tsx
  components/composite/StepShipping/index.tsx
  components/data/AppProvider/utils.ts
  components/data/GlobalStylesProvider/index.tsx
  components/ui/Logo/index.tsx
  components/ui/StepHeader/index.tsx
  package.json
  pages/Order.tsx
  pnpm-lock.yaml
  specs/e2e/checkout-digital.spec.ts
  specs/e2e/language.spec.ts
  specs/e2e/payments-adyen-klarna.spec.ts
  specs/fixtures/CheckoutPage.ts
  specs/fixtures/tokenizedPage.ts
  utils/getSettings.ts
Labels: Enahancement

#372 Update selector for Klarna payment terms checkbox (german)
  specs/fixtures/CheckoutPage.ts
Labels: bug

#375 Improve checkout load time making two setup calls in parallel
  utils/getSettings.ts
Labels: Enahancement

#380 Fix/update packages
  package.json
  pnpm-lock.yaml
Labels: bug

#382 Add deploy buttons for Netlify and Vercel
  .node-version
  README.md
  netlify.toml
  vercel.json
Labels: documentation
