Repository commercelayer/mfe-checkout, pull requests merged in 2025-05, with the labels that each got.

#517 Add support to order `token` attribute on organization config URLs
  .circleci/config.yml
  components/composite/OrderSummary/LineItemTypes/index.tsx
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  specs/e2e/thank-you-page.spec.ts
  specs/fixtures/CheckoutPage.ts
  specs/fixtures/tokenizedPage.ts
  utils/getSettings.ts
Labels: Enhancement

#521 Potential fix for code scanning alert no. 3: Workflow does not contain permissions
  .github/workflows/release.yml
Labels: task

#526 Enforce rule of hooks and avoid calling hooks conditionally
  biome.json
  components/composite/OrderSummary/ReturnToCart/index.tsx
  components/composite/StepCustomer/AddressInputGroup/index.tsx
  components/composite/StepCustomer/index.tsx
  components/composite/StepPayment/index.tsx
  components/composite/StepShipping/Errors/NoShippingMethods.tsx
  components/composite/StepShipping/Errors/OutOfStock.tsx
  components/composite/StepShipping/index.tsx
  components/data/GTMProvider/index.tsx
  components/hooks/useActiveStep.ts
Labels: bug

#525 Update CKO drop-in
  README.md
  components/composite/StepPayment/PaymentContainer/index.tsx
  components/composite/StepPayment/styled.tsx
  components/composite/StepPlaceOrder/styled.tsx
  package.json
  pnpm-lock.yaml
  specs/e2e/payments-checkoutcom.spec.ts
  specs/fixtures/CheckoutPage.ts
  tsconfig.json
Labels: Enhancement
